# Generated by Django 3.1.6 on 2021-05-28 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daBookStore', '0003_checklists_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklists',
            name='values',
        ),
    ]
